### PR TITLE
Add HTTPS InfluxDB test

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
Note that this first test (26f8f68) should *not* work.

**Comment by dberzano** [comment]
It correctly failed, as the certificate was unverifiable. Now trying with `insecure_https` in the conf.

**Review by mconcas — APPROVED** [review]
It looks like the test passed the test.

**Comment by dberzano** [comment]
For future reference, most of the information was taken from [the official influxdb Docker container documentation](https://hub.docker.com/_/influxdb/).

**Pull request merged**
